#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment ROOTDIR SRCDIR MANDIR LIBDIR BINDIR ENSEMBL_SERVERROOT

if [ ! -d $ROOTDIR ]
then
	mkdir $ROOTDIR
	if [ $? != 0 ]
	then
		echo "Not able to create $ROOTDIR"
		exit
	fi
fi

if [ ! -d $SRCDIR ]
then
    mkdir $SRCDIR
fi
if [ ! -d $MANDIR ]
then
    mkdir $MANDIR
fi
if [ ! -d $LIBDIR ]
then
    mkdir $LIBDIR
fi
if [ ! -d $BINDIR ]
then
    mkdir $BINDIR
fi

if [ ! -d $ENSEMBL_SERVERROOT ]
then
    mkdir $ENSEMBL_SERVERROOT
fi

if [ ! -d $HOME/.cpan ]
then
    mkdir $HOME/.cpan
fi

if [ ! -d $HOME/.cpan/CPAN ]
then
    mkdir $HOME/.cpan/CPAN
fi

if [ ! -d $HOME/.cpan/build ]
then
    mkdir $HOME/.cpan/build
fi

if [ ! -d $HOME/.cpan/sources ]
then
    mkdir $HOME/.cpan/sources
fi
