#!/bin/sh

CONFIGFILE=$1

if [ ! $CONFIGFILE ]
then
	echo "Usage: $0 set_environment"
	exit
fi

. $CONFIGFILE

if [ ! $INSTALLSCRIPTDIR ]
then
	echo "\$INSTALLSCRIPTDIR not set. Don't know where the scripts are."
	exit
fi


. $INSTALLSCRIPTDIR/create_directories
if [ "$PERL" = "" ] || [ ! -x $PERL ] ; then
    . $INSTALLSCRIPTDIR/install_perl
fi
. $INSTALLSCRIPTDIR/check_environment PERL

$PERL $INSTALLSCRIPTDIR/configure_cpan.pl $HOME/.cpan/CPAN/MyConfig.pm
if [ "$MYSQL_INCLUDE_DIR" = "" ] || [ "$MYSQL_LIB_DIR" = "" ] ; then
    . $INSTALLSCRIPTDIR/install_mysql
fi
. $INSTALLSCRIPTDIR/check_environment MYSQL_INCLUDE_DIR MYSQL_LIB_DIR

. $INSTALLSCRIPTDIR/install_perlmodules
. $INSTALLSCRIPTDIR/install_apache
. $INSTALLSCRIPTDIR/check_environment BINDIR
# shut down the mysql daemon (was left on for testing)
$BINDIR/mysqladmin -u root --password='' shutdown
. $INSTALLSCRIPTDIR/install_biomodules
. $INSTALLSCRIPTDIR/check_environment ENSEMBL_SERVERROOT
$PERL $INSTALLSCRIPTDIR/configure_defs.pl $ENSEMBL_SERVERROOT/conf/SiteDefs.pm
$PERL $INSTALLSCRIPTDIR/configure_defs.pl $ENSEMBL_SERVERROOT/conf/Homo_sapiens_Defs.pm
$ENSEMBL_SERVERROOT/bin/apachectl start

echo
echo "Now forward local port $FORWARDED_DB_PORT to port 3306 of the DB server."
echo
echo "e.g.: ssh -L $FORWARDED_DB_PORT:$DB_HOST:3306 computer.in.dbhost.domain"
echo
