#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment SRCDIR PERL ENSEMBL_SERVERROOT APACHE_VERSION

# get and unpack mod_perl
echo
echo "Downloading mod_perl"
echo
cd $HOME/.cpan/build
wget http://www.perl.com/cgi-bin/cpan_mod?module=mod_perl --passive-ftp
gtar xvzf mod_perl*
rm mod_perl*.tar.gz
#wget http://$CPAN_SITE/modules/by-module/Apache/$MODPERL_VERSION.tar.gz
#gtar xvzf $MODPERL_VERSION.tar.gz

# get and unpack Apache
echo
echo "Downloading Apache"
echo
cd $SRCDIR
wget http://httpd.apache.org/dist/httpd/$APACHE_VERSION.tar.gz --passive-ftp
gtar xvzf $APACHE_VERSION.tar.gz
rm $APACHE_VERSION.tar.gz
# install mod_perl
echo
echo "Installing mod_perl"
echo
cd $HOME/.cpan/build/mod_perl*
$PERL Makefile.PL APACHE_SRC=$SRCDIR/$APACHE_VERSION/src DO_HTTPD=1 USE_APACI=1 EVERYTHING=1 
make
make test
make install

# install Apache
echo
echo "Installing Apache"
echo
cd $SRCDIR/$APACHE_VERSION
./configure \
	--prefix=$ENSEMBL_SERVERROOT \
	--with-perl=$PERL \
	--activate-module=src/modules/perl/libperl.a
make
make install

# conf and htdocs will come from ensembl-mirror, i.e. basically we could
# remove them at this point
mv $ENSEMBL_SERVERROOT/conf $ENSEMBL_SERVERROOT/conf.apache
mv $ENSEMBL_SERVERROOT/htdocs $ENSEMBL_SERVERROOT/htdocs.apache
