#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment ROOTDIR PERL GD_VERSION EXPAT_VERSION MYSQL_INCLUDE_DIR MYSQL_LIB_DIR

# configure CPAN stuff
echo
echo "Creating ~/.cpan/CPAN/MyConfig.pm"
echo
$PERL $INSTALLSCRIPTDIR/configure_cpan.pl ~/.cpan/CPAN/MyConfig.pm

# install URI, Net::FTP, MIME::Base64, Digest::MD5, HTML::Tagset,
# HTML::Parser, HTML::HeadParser and LWP
echo
echo "Installing Bundle::LWP"
echo
$PERL -MCPAN -e 'install Bundle::LWP' < /dev/null  

# download DBD::mysql and DBI
# NOTE: installation of DBD::mysql does not work here, since
# location of mysql headers and libs are not known by default
echo
echo "Installing Bundle::DBD::mysql"
echo
$PERL -MCPAN -e 'install Bundle::DBD::mysql'     

# install DBD::mysql
cd $HOME/.cpan/build/DBD-mysql*
$PERL Makefile.PL \
	--cflags=-I$MYSQL_INCLUDE_DIR \
	--libs="-L$MYSQL_LIB_DIR -lmysqlclient -lz"
#	--cflags=-I$ROOTDIR/include/mysql \
#	--libs="-L$ROOTDIR/lib/mysql -lmysqlclient -lz"

make
make test
make install

# download and install GD-1.18
echo
echo "Installing GD"
echo
cd $HOME/.cpan/build
wget http://$CPAN_SITE/modules/by-authors/Lincoln_D_Stein/$GD_VERSION.tar.gz --passive-ftp
gtar xvzf $GD_VERSION.tar.gz
rm $GD_VERSION.tar.gz
cd $GD_VERSION
$PERL Makefile.PL
make
make test
make install

# expat, necessary for XML::Parser
echo
echo "Installing expat"
echo
cd $ROOTDIR/src
wget http://download.sourceforge.net/expat/$EXPAT_VERSION.tar.gz --passive-ftp
gtar xvzf $EXPAT_VERSION.tar.gz
rm $EXPAT_VERSION.tar.gz
cd $EXPAT_VERSION
./configure --prefix=$ROOTDIR
make
make install

# XML::Parser
echo
echo "Installing XML::Parser"
echo
cd $HOME/.cpan/build
$PERL -MCPAN -e 'get XML::Parser'
cd $HOME/.cpan/build/XML-Parser*
$PERL Makefile.PL \
	EXPATLIBPATH=$ROOTDIR/lib \
	EXPATINCPATH=$ROOTDIR/include
make
make test
make install

# Storable
# Can't use cpan shell for some reason !?
echo
echo "Installing Storable"
echo
cd $HOME/.cpan/build
wget http://www.perl.com/cgi-bin/cpan_mod?module=Storable --passive-ftp
gtar xvzf Storable*
rm Storable*.tar.gz
cd Storable*
$PERL Makefile.PL
make
make test
make install

# install Apache::DBI
echo
echo "Installing Apache::DBI"
echo
$PERL -MCPAN -e 'install Apache::DBI'

# install IO::String
echo
echo "Installing IO::String"
echo
$PERL -MCPAN -e 'install IO::String'



