#!/bin/sh

# source this one to get $PERL set

$INSTALLSCRIPTDIR/check_environment SRCDIR CC CPAN_SITE

cd $SRCDIR

# get perl
echo "wget http://$CPAN_SITE/src/stable.tar.gz"
wget http://$CPAN_SITE/src/stable.tar.gz --passive-ftp

# unpack it an store the log for extracting the dir name
gtar xvzf stable.tar.gz > $PID.tmp 2>&1
rm stable.tar.gz

# extract the dir name
PERLDIR=`sed '1 q' < $PID.tmp`
rm $PID.tmp

echo "PERLDIR is $PERLDIR"
cd $PERLDIR
# run configure script
echo "sh Configure -Dprefix=$ROOTDIR -Dcc=$CC -Uinstallusrbinperl -des"
sh Configure -Dprefix=$ROOTDIR -Dcc=$CC -Uinstallusrbinperl -des
echo "make"
make
echo "make test"
make test
echo "make install"
make install
echo "cd ../.."
cd ../..
export PERL=$ROOTDIR/bin/perl

if [ ! -x $PERL ]
then
    echo "$PERL does not exist or is not executable."
    echo "Something hs gobe wrong with perl installation."
    exit
fi
