#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment SRCDIR BINDIR ENSEMBL_DBPASS

cd $SRCDIR

# get and install MySQL
echo
echo "Installing mysql"
echo

MYSQLVERSION=${MYSQLVERSION:-mysql-3.23.40}
echo "Downloading MySQL [$MYSQLVERSION]"
wget http://download.sourceforge.net/mysql/$MYSQLVERSION.tar.gz
gtar xvzf $MYSQLVERSION.tar.gz
rm $MYSQLVERSION.tar.gz
echo "cd $MYSQLVERSION"
cd $MYSQLVERSION
echo "./configure --prefix=$ROOTDIR"
./configure --prefix=$ROOTDIR #\
			      #--without-server
# Uncomment above to install just client and libs
echo "make"
make
echo "make test"
make test
echo "make install"
make install
echo "scripts/mysql_install_db"
scripts/mysql_install_db 
# start MySQL daemon
echo "$BINDIR/safe_mysqld &"
$BINDIR/safe_mysqld &
# wait for the server to start up
sleep 5
# set the root password
if [ "$ENSEMBL_DBPASS" != "" ]
then
    $BINDIR/mysqladmin -u root --password='' password $ENSEMBL_DBPASS
fi
export MYSQL_INCLUDE_DIR=$ROOTDIR/include/mysql
export MYSQL_LIB_DIR=$ROOTDIR/lib/mysql

#Leave it on for testing
#$BINDIR/mysqladmin -u root -p$ENSEMBL_DBPASS shutdown
