#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment ENSEMBL_SERVERROOT PERL ENSEMBL_DB_BRANCH ENSEMBL_WEB_BRANCH ENSEMBL_BIOPERL_BRANCH

cd $ENSEMBL_SERVERROOT

# get ensembl-api
echo
echo "Installing ensembl-api"
echo
cat << _HERE_ | cvs -d :pserver:cvsuser@cvs.sanger.ac.uk:/cvsroot/ensembl co -r $ENSEMBL_DB_BRANCH ensembl-api
CVSUSER
_HERE_

# get ensembl-web
echo
echo "Installing ensembl-web"
echo
cat << _HERE_ | cvs -d :pserver:cvsuser@cvs.sanger.ac.uk:/cvsroot/ensembl co -r $ENSEMBL_WEB_BRANCH ensembl-web
CVSUSER
_HERE_

# get bioperl
echo
echo "Installing Bioperl"
echo
cat << _HERE_ | cvs -d :pserver:cvs@cvs.bioperl.org:/home/repository/bioperl co -r $ENSEMBL_BIOPERL_BRANCH bioperl-live
cvs
_HERE_

# get and install das
echo
echo "Installing Bio::Das"
echo
cat << _HERE_ | cvs -d :pserver:cvs@cvs.biodas.org:/home/repository/biodas checkout das
cvs    
_HERE_
cd das/Bio-Das
$PERL Makefile.PL
make && make install
cd ../..

# create missing dirs
echo
echo "Creating missing directories"
echo
mkdir htdocs/gfx/clone
mkdir htdocs/gfx/gene
mkdir htdocs/gfx/image_tmp

echo
echo "Reconfiguring httpd.conf"
echo
mv conf/httpd.conf conf/httpd.conf.ori
$PERL -pe 's/^\#!\S+perl/\#\!$ENV{'PERL'}/' < conf/httpd.conf.ori > conf/httpd.conf


















