#!/bin/sh

CONFIGFILE=$1

if [ ! $CONFIGFILE ]
then
	echo "Usage: $0 set_environment"
	exit
fi

. $CONFIGFILE

if [ ! $INSTALLSCRIPTDIR ]
then
	echo "\$INSTALLSCRIPTDIR not set. Don't know where the scripts are."
	exit
fi


. $INSTALLSCRIPTDIR/create_directories
. $INSTALLSCRIPTDIR/install_perl
. $INSTALLSCRIPTDIR/check_environment PERL
$PERL $INSTALLSCRIPTDIR/configure_cpan.pl $HOME/.cpan/CPAN/MyConfig.pm
. $INSTALLSCRIPTDIR/install_apache
. $INSTALLSCRIPTDIR/install_mysql
. $INSTALLSCRIPTDIR/install_perlmodules
. $INSTALLSCRIPTDIR/install_biomodules
. $INSTALLSCRIPTDIR/check_environment ENSEMBL_SERVERROOT
$PERL $INSTALLSCRIPTDIR/configure_defs.pl $ENSEMBL_SERVERROOT/conf/SiteDefs.pm
$PERL $INSTALLSCRIPTDIR/configure_defs.pl $ENSEMBL_SERVERROOT/conf/Homo_sapiens_Defs.pm
$ENSEMBL_SERVERROOT/bin/apachectl start

