#!/bin/sh

. $INSTALLSCRIPTDIR/check_environment ENSEMBL_HOST ENSEMBL_DBUSER ENSEMBL_DBPASS ENSEMBL_HOST_PORT BINDIR

mysqladmin=$BINDIR/mysqladmin
mysql=$BINDIR/mysql
mysqlimport=$BINDIR/mysqlimport 


SCHEMA_GZ=*.sql.gz
echo $SCHEMA_GZ
DB_NAME=`echo $SCHEMA_GZ | sed 's/\.sql\.gz//'`
echo $DB_NAME

$mysqladmin \
    -u $ENSEMBL_DBUSER \
    -h $ENSEMBL_HOST \
    -p$ENSEMBL_DBPASS \
    -P $ENSEMBL_HOST_PORT \
    create $DB_NAME

if [ $? != 0 ]; then
    echo "Creating $DB_NAME failed! Exiting."
    exit 1
fi

gunzip -c $SCHEMA_GZ | \
    $mysql \
	-u $ENSEMBL_DBUSER \
	-h $ENSEMBL_HOST \
	-p$ENSEMBL_DBPASS \
	-P $ENSEMBL_HOST_PORT \
	$DB_NAME

if [ $? != 0 ]; then
    echo "Table creation failed! Exiting."
    exit 2
fi

# all tables except dna
for i in *table.gz; do
    TABLE=`echo $i | sed 's/\.gz//;'`
    echo $TABLE
    echo mkfifo $TABLE
    `mkfifo $TABLE`
    echo "gunzip -c $i > $TABLE &"
    `gunzip -c $i > $TABLE` &
    $mysqlimport \
	-u $ENSEMBL_DBUSER \
	-h $ENSEMBL_HOST \
	-p$ENSEMBL_DBPASS \
	-P $ENSEMBL_HOST_PORT \
	$DB_NAME $TABLE
    rm -f $TABLE
    if [ $? != 0 ]; then
	echo "Importing $TABLE failed! Exiting."
	exit 3
    fi
done

# dna table
DNA_FILES=`ls dna-table*.gz 2>/dev/null`
if [ "$DNA_FILES" != "" ]; then
    echo $DNA_FILES
    echo mkfifo dna.txt.table
    `mkfifo dna.txt.table`
    echo "gunzip -c dna-table*.gz > dna.txt.table &"
    `gunzip -c dna-table*.gz > dna.txt.table` &
    $mysqlimport \
	-u $ENSEMBL_DBUSER \
	-h $ENSEMBL_HOST \
	-p$ENSEMBL_DBPASS \
	-P $ENSEMBL_HOST_PORT \
	$DB_NAME dna.txt.table
    rm -f dna.txt.table
    if [ $? != 0 ]; then
	echo "Importing dna.txt.table failed! Exiting."
	exit 4
    fi    
fi

