#!/bin/sh

#various directories
export INSTALLSCRIPTDIR=$HOME/installscripts
export ROOTDIR=$PWD
export SRCDIR=$ROOTDIR/src
export MANDIR=$ROOTDIR/man
export LIBDIR=$ROOTDIR/lib
export BINDIR=$ROOTDIR/bin
export ENSEMBL_SERVERROOT=$ROOTDIR/ensemblroot

# compiler to be used
export CC=cc

# 
export CPAN_SITE=cpan.org

#things to be installed
export EXPAT_VERSION=expat-1.95.1
export STORABLE_VERSION=Storable-1.0.13
export MYSQL_VERSION=mysql-3.23.40
export MODPERL_VERSION=mod_perl-1.26
export APACHE_VERSION=apache_1.3.20
export GD_VERSION=GD-1.18
export ENSEMBL_DB_BRANCH=branch-ensembl-110
export ENSEMBL_WEB_BRANCH=branch-ensembl-112
export ENSEMBL_BIOPERL_BRANCH=branch-07

# mysql server related
# if envs MYSQL_TCP_PORT and MYSQL_UNIX_PORT are set, mysql daemon
# is started up with this port and socket
# define LOCAL_DB_PASS in your shell
export MYSQL_ROOT=root
export MYSQL_PASS=$LOCAL_DB_PASS
export MYSQL_TCP_PORT=3307
export MYSQL_UNIX_PORT=/tmp/my_own_mysqld.sock


# web server related
export ENSEMBL_USER=$USER
export ENSEMBL_GROUP=$GROUP
export ENSEMBL_SERVERADMIN=vastrik@ebi.ac.uk
export ENSEMBL_PORT=8080
export ENSEMBL_SERVERNAME=$HOST
export ENSEMBL_MAIL_ERRORS=$ENSEMBL_SERVERADMIN

#
# location of databases, usernames, passwds
#
# "main" dbs
export ENSEMBL_HOST=$ENSEMBL_SERVERNAME
export ENSEMBL_DBUSER=$MYSQL_ROOT
export ENSEMBL_DBPASS=$MYSQL_PASS
export ENSEMBL_HOST_PORT=$MYSQL_TCP_PORT

# userdb
export ENSEMBL_USERDB_HOST=$ENSEMBL_SERVERNAME
export ENSEMBL_USERDB_USER=$MYSQL_ROOT
export ENSEMBL_USERDB_PASS=$ENSEMBL_DBPASS      

# help db
export ENSEMBL_HELP_HOST=$ENSEMBL_SERVERNAME
export ENSEMBL_HELP_DBUSER=$MYSQL_ROOT
export ENSEMBL_HELP_DBPASS=$ENSEMBL_DBPASS
export ENSEMBL_HELP_PORT=$MYSQL_TCP_PORT

