#
# Test-job template
#

variables:
   USER: "gitlabci"
   MYSQL_ROOT_PASSWORD: "n0t4t4l1s3cur3!"

.ensembl_test_template:
  services:
     - name: mysql:5.7
       alias: mysqldb

  image: dockerhub.ebi.ac.uk/ensembl-infrastructure/ensembl-ci-docker-images:${PERL_VERSION}

  before_script:
    - echo "CI_COMMIT_BRANCH = $CI_COMMIT_BRANCH"
    - echo "CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME"
    - export ENSEMBL_BRANCH='main'
    - export ENSEMBL_VER=$(echo $TRAVIS_BRANCH | grep -P -o '(?<=version[\W_]|fix[\W_]|release[\W_])(\d+)')
    - if [[ $ENSEMBL_VER =~ [0-9]+ ]]; then ENSEMBL_BRANCH="release/$ENSEMBL_VER"; fi
    - git clone --branch=$ENSEMBL_BRANCH --depth=1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch=$ENSEMBL_BRANCH --depth=1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch=$ENSEMBL_BRANCH --depth=1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch=$ENSEMBL_BRANCH --depth=1 https://github.com/Ensembl/ensembl-compara.git
    - cpanm --installdeps --notest . --with-all-features
    - cpanm -n Devel::Cover::Report::Coveralls DBD::SQLite
    - cp travisci/MultiTestDB.conf.gitlabci.mysql  modules/t/MultiTestDB.conf.mysql
    - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
    - cp travisci/testdb.conf.gitlabci.mysql  testdb.conf.mysql
    - cp travisci/testdb.conf.travisci.SQLite testdb.conf.SQLite

  tags:
    - dind

#
# Test jobs
#

test:perl5.26-sqlite:
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.26"
    COVERALLS: "false"
    DB: "sqlite"
  script:
    - ./travisci/harness.sh

test:perl5.26-mysql:
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.26"
    # Note: relies on the secret variable COVERALLS_REPO_TOKEN for report uploads to work
    COVERALLS: "false"
    DB: "mysql"
  script:
    - ./travisci/harness.sh

test:perl5.38-sqlite:
  stage: test
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.38"
    COVERALLS: "false"
    DB: "sqlite"
  script:
    - ./travisci/harness.sh

#
# Triggers for dependent builds
#

# Removed the dependent builds triggered from GitLab
# Travis cfg is not allowing concurrent build anymore
# and dep build requests are timing out
# Better remove them - for now
