#!/usr/local/bin/perl

use strict;

=head1 NAME


=head1 SYNOPSIS


=head1 DESCRIPTION


=cut

use Bio::EnsEMBL::Analysis::PepAlign;
use Bio::EnsEMBL::Pep_SeqFeature;
use Bio::EnsEMBL::Analysis::Log;
use Bio::EnsEMBL::FeaturePair;

use Getopt::Long;

my ($coord,$frac) = @ARGV;

 
my $pair      = new Bio::EnsEMBL::Analysis::PepAlign;

my $dna_homol = make_test_homol(10,1,
				2,-1,
				1,
				1,3);
$pair->addFeaturePair($dna_homol);


my $pair1  = $dna_homol;
my $pair2  = $dna_homol->feature2;

print($pair1->start . " " . 
      $pair1->end   . " " . 
      $pair2->start . " " . 
      $pair2->end   . "\n");


my ($out) = $pair->pep2cDNA($coord,$frac);
#    my ($out,$frac) = $pair->cDNA2pep($c);
print("pep $coord ($frac) - cDNA $out\n");

	

sub make_test_homol {
    my ($dnastart,$dnastrand,$pepstart,$pepstrand,$peplen,$sfrac,$efrac) = @_;

    my $dnaend;
    my $pepend;
    
    if ($pepstrand == 1) {
	$dnaend = $dnastart + 3*$peplen  + $efrac - 1;
	$pepend = $pepstart + $peplen;
	
	$dnastart -= (4-$sfrac);
	$pepstart--;

    } else {
	$dnaend = $dnastart + 3*$peplen + (4-$sfrac) - 1;
	$pepend = $pepstart + $peplen;

	$dnastart -= $efrac;
	$pepstart--;
    }
	
    print("Dna start end $dnastart $dnaend\n");
    print("Pep start end $pepstart $pepend\n");
    print("Start/end frac $sfrac $efrac $peplen\n");

    my $dna_homol = new Bio::EnsEMBL::SeqFeature      (-start => $dnastart,
						       -end   => $dnaend,
						       -strand => $dnastrand,
						     );

    my $pep_homol = new Bio::EnsEMBL::Pep_SeqFeature(-start => $pepstart,
						     -end   => $pepend,
						     -strand => $pepstrand,
						     -start_frac => $sfrac,
						     -end_frac => $efrac,
						     );
    my $pair = new Bio::EnsEMBL::FeaturePair(-feature1 => $dna_homol,
					     -feature2 => $pep_homol,
					     );

    
    return $pair;
}







