#!/usr/local/bin/perl

BEGIN {
    unshift (@INC,"/nfs/disk89/michele/bioperl-live");
    unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/modules");
}

# Let the code begin...


use Bio::EnsEMBL::DBSQL::Obj;

use Getopt::Long;
use strict;

my ($clonefile,
    $clone,
    $test,
);


GetOptions("clonefile=s" => \$clonefile,            # File of clone names
	   "clone=s"     => \$clone,                # Clone name on the command line
	   ) or usage();

my @clones = read_clones($clonefile,$clone);

my  $db         = Bio::EnsEMBL::DBSQL::Obj->new(-dbname => 'pogdev',
						-host   => 'obi-wan',
						-user   => 'ensdev',
						)  or die "Can't connect to database";


foreach my $clone (@clones) {
         print("Deleting clone $clone\n");
	$db->delete_Clone($clone);
}
sub read_clones {
    my ($clonefile,$clone) = @_;

    my @clones;

    if (defined($clonefile)) {
	open(IN,"<$clonefile") || die "Couldn't open $clonefile";
	while (<IN>) {
	    chomp;
	    push(@clones,$_);
	}
    }
    push(@clones,$clone);

    return @clones;
}

