#!/usr/local/bin/perl

BEGIN {
    unshift (@INC,"/nfs/disk89/michele/pogdir/bioperl-live");
    unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/modules");
}

# Let the code begin...


use Bio::EnsEMBL::Analysis::GFF;
use Bio::EnsEMBL::Analysis::Analysis;
use Bio::EnsEMBL::Analysis::MSPType;

use Bio::EnsEMBL::DBSQL::Obj;
use Bio::EnsEMBL::DBSQL::Contig;

use Getopt::Long;
use strict;

my ($clonefile,
    $clone,
);


GetOptions("clonefile=s" => \$clonefile,            # File of clone names
	   "clone=s"     => \$clone,                # Clone name on the command line
	   ) or usage();

# Connect to the database
my @clones     = read_clones($clonefile,$clone);

my $db         = Bio::EnsEMBL::DBSQL::Obj->new(-dbname => 'ensdev',
					       -host   => 'obi-wan',
					       -user   => 'ensdev',
					       )  or die "Can't connect to database";

CLONE: foreach my $cloneid (@clones) {

    print("\nProcessing clone $cloneid\n");

#    eval{
	my $accession  = get_accession($cloneid); print(STDERR " - accession for clone is $accession\n");

	next CLONE if ($accession eq "");

	my $cloneobj   = $db      ->get_Clone($accession) || next CLONE;
	my @contigs    = $cloneobj->get_all_Contigs();

	print("Number of contigs found is " . (1+$#contigs) . "\n");
	
	# Initialize directories and clone/contig names
	
	my $root_dir   = "/nfs/disk100/humpub/th/unfinished_ana/data/$cloneid/";
	
	CONTIG: foreach my $contig (@contigs) {
	    print(" - Processing contig " . $contig->id . "\n");

	    my $contigid   = $contig->id;
	    (my $contigno  = $contigid) =~ s/.*\.(.*)/$1/;
	    
	    my $repeatfile = $root_dir . "/" . $clone . "." . $contigno . ".RepMask.out.gff";
	
	    print("Repeat file is $repeatfile\n");
	    if (! -e $repeatfile) {
		print(STDERR "Can't find repeat file $repeatfile. Skipping contig\n");
		next CONTIG;
	    }

	    my $GFF        = new Bio::EnsEMBL::Analysis::GFF(-file => $repeatfile);

	    print("done gff\n");

	    my $analysis   = make_analysis($repeatfile);
	    my $analysisid = $db->write_Analysis($analysis);
	    
	    foreach my $f ($GFF->each_Feature) {
		$db->write_Homol_Feature($f,$analysisid,$contig);
	    }

	}
#    }; 
#
#    if (@_) {
#	print(STDERR "@_");
#	next CLONE;
#    }
}




sub get_accession {
    my ($cloneid) = @_;

    if ($cloneid =~ /^AC/) {
	return $cloneid;
    }

    open (IN,"clone2accession $cloneid |");

    my $line = <IN>;
    chomp($line);
    my ($clone,$acc) = split(' ',$line);

    if ($acc eq "") {
	print(STDERR "Couldn't fetch accession no. for clone $cloneid\n");
	return;
    } else {
	return $acc;
    }
}
sub read_clones {
    my ($clonefile,$clone) = @_;

    my @clones;

    if (defined($clonefile)) {
	open(IN,"<$clonefile") || die "Couldn't open $clonefile";
	while (<IN>) {
	    chomp;
	    push(@clones,$_);
	}
    }
    push(@clones,$clone);

    return @clones;
}

sub make_analysis {
    my ($file) = @_;

    my $ext;

    if ($file =~ /msptmp$/) {
	($ext  = $file) =~ s/.*(\..*.msptmp)/$1/;
    } elsif ($file =~ /RepMask.out.gff/) {
	$ext = ".RepMask.out.gff";
    }

    my $test    = Bio::EnsEMBL::Analysis::MSPType->each_MSPType;
    my $MSPType = Bio::EnsEMBL::Analysis::MSPType->extension2MSPType($ext);
    
    my $anal = new Bio::EnsEMBL::Analysis::Analysis;
    
    $anal->db             ($MSPType->[2]);
    $anal->db_version     ($MSPType->[6]);
    $anal->program        ($MSPType->[1]);
    $anal->program_version($MSPType->[7]);
    $anal->gff_source     ($MSPType->[1]);
    $anal->gff_feature    ($MSPType->[8]);
    
    return $anal;
}
    
sub accession2clone {
    my ($acc) = @_;

    open(IN,"efetch EM:$acc |grep \"^DE\" |");

    while (my $line = <IN>) {
	if ($line =~ /.* from clone +(.*)\n$/) {
	    my $clone = $1;
	    print("clone is $clone\n");
	    close(IN);
	    return $clone;
	}
    }
}
