#!/usr/local/bin/perl

BEGIN {
    unshift (@INC,"/nfs/disk89/michele/bioperl-live/");
    unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/modules");
}

use strict;

use Bio::EnsEMBL::SeqFeature;
use Bio::EnsEMBL::FeaturePair;
use Bio::EnsEMBL::Analysis::Analysis;
use Bio::SeqFeature::Generic;
use Bio::SeqFeature::FeaturePair;

my $f1 = new Bio::EnsEMBL::SeqFeature(-seqname => "pog1",
                                      -start   => 100,
				      -end     => 200,
				      -strand  => 1,
				      -frame   => 2,
				      -score   => 250.0,
				      -source_tag  => "pogsource",
				      -primary_tag => "pogprimary",
				      );


my $f2 = new Bio::EnsEMBL::SeqFeature(-seqname => "pog2",
                                      -start   => 150,
				      -end     => 250,
				      -strand  => -1,
				      -frame   => 1,
				      -score   => 350.0,
				      -source_tag  => "pogsource2",
				      -primary_tag => "pogprimary2",
				      );



my $analysis = new Bio::EnsEMBL::Analysis::Analysis(-db => 'pogdb',
						    -db_version => 1.0,
						    -program => "pogprog",
						    -program_version => 2.0,
						    -gff_source => 'anasource',
						    -gff_feature => 'anafeature',
						    );


my $fp = new Bio::SeqFeature::FeaturePair(-feature1 => $f1,
					  -feature2 => $f2,
					  );



print("Start/end " . $fp->seqname . " " . 
      $fp->start      . " " . 
      $fp->end        . " " . 
      $fp->score      . " " . 
      $fp->strand     . " " . 
      $fp->frame      . " " . 
      $fp->source_tag . " " .
      $fp->primary_tag ."\n");

print("Start/end " . $fp->hseqname . " " .
      $fp->hstart . " " . 
      $fp->hend . " " .
      $fp->hscore . " " . 
      $fp->hstrand . " " . 
      $fp->hframe . " " . 
      $fp->hsource_tag . " " .
      $fp->hprimary_tag ."\n");


print("Inverting\n");

$fp->invert;

print("Start/end " . $fp->seqname . " " . 
      $fp->start      . " " . 
      $fp->end        . " " . 
      $fp->score      . " " . 
      $fp->strand     . " " . 
      $fp->frame      . " " . 
      $fp->source_tag . " " .
      $fp->primary_tag ."\n");

print("Start/end " . $fp->hseqname . " " .
      $fp->hstart . " " . 
      $fp->hend . " " .
      $fp->hscore . " " . 
      $fp->hstrand . " " . 
      $fp->hframe . " " . 
      $fp->hsource_tag . " " .
      $fp->hprimary_tag ."\n");


