#!/usr/local/bin/perl


my $previous = -1;
my $prevcontig = -1;
my $geneid = 0;

while (<>) {
      chomp;

      my @f = split(/,/,$_);

      my $type   = $f[10];
      my $contig = $f[1];

      $type =~ s/\'//g;

      if ($type =~ /Initial/ ||
	  $type =~ /Single/  ||
	  $previous =~  /Single/ ||
	  $previous =~  /Terminal/ ||
	  $previous == -1 ||
	  $contig != $prevcontig) {
	
	$geneid++;
	
      }

      $f[10] = "\'$geneid\'";      

      my $string = join(",",@f);
      
#      print "\n" . $_ . "\n";
#      print $string . "\n";
      
      $previous = $type;
      $prevcontig = $contig;

    }
