#!/usr/local/bin/perl

use strict;

use Bio::EnsEMBL::DBSQL::DBAdaptor;
use Bio::EnsEMBL::PerlDB::Clone;
use Bio::EnsEMBL::PerlDB::Contig;

use Getopt::Long;

my $host     = 'ecs1a';
my $dbname   = 'mouse_sc011015_alistair';
my $newhost  = 'ecs1f';
my $newdbname = 'mouse_denormalize_test2';
my $newpath   = 'CHR';
my $dbuser   = 'ensadmin';
my $pass     = 'ensembl';
my $path     = 'sanger_20011015_2';
my $genes    = 0;
my $feature  = 0;
my $genewise = 0;
my $repeat   = 0;
my $chunk    = 5000000;
my $threshold = 0;
my $chr_name;

$| = 1;

&GetOptions( 'host:s'    => \$host,
             'dbuser:s'  => \$dbuser,
             'dbname:s'  => \$dbname,
	     'genes'     => \$genes,
	     'feature'   => \$feature,
	     'repeat'    => \$repeat,
             'path=s'    => \$path,
             'pass:s'    => \$pass,
	     'chunk:n'   => \$chunk,
	     'threshold:n' => \$threshold,
	     'chrname:s'   => \$chr_name,
             );

print STDERR "Time in dumpgff " . time . "\n";

my $db = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host             => $host,
					    -user             => $dbuser,
					    -dbname           => $dbname,
                                            -pass             => $pass,
					    -perlonlyfeatures => 0);

my $newdb = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host             => $newhost,
					       -user             => $dbuser,
					       -dbname           => $newdbname,
					       -pass             => $pass,
					       -perlonlyfeatures => 0);

print STDERR "Time after db  " . time . "\n";

print STDERR "Connected to database\n";

$db->static_golden_path_type($path);

my $stadp = $db->get_StaticGoldenPathAdaptor();


my @chr   = $stadp->get_all_chromosome_name;

my %analysis;

CHR: foreach my $chr (@chr) {
  next CHR unless $chr eq $chr_name;

  my $length = $stadp->get_chromosome_length($chr);
  print STDERR "Chromosome $chr length $length\n";

  my $current = 1;
  
  while ($current <= $length) {
    print STDERR "Time before chunk " . time . "\n";
    my $end = $current + $chunk -1;

    if ($end > $length) {
      $end = $length;
    }
    
    my $vc    = $stadp->fetch_VirtualContig_by_chr_start_end($chr,
							     $current,
							     $end
							    );

    my @repeats  = $vc->get_all_RepeatFeatures      if ($repeat);
    my @feat     = $vc->get_all_SimilarityFeatures  if ($feature);

    my $seq      = $vc->primary_seq;

    my $bioseq = new Bio::Seq($seq->seq);

    print STDERR "Seq is $seq " . scalar(@repeats) . " " . scalar(@feat) . "\n";
    my $cloneid  = $chr . ".$current-$end";

    my $clone     = new Bio::EnsEMBL::PerlDB::Clone;

    $clone->htg_phase(3);
    $clone->id($cloneid);
    
    my $contigid = $cloneid;
    ;
    my $contig   = new Bio::EnsEMBL::PerlDB::Contig;
    
    $contig->id($contigid);
    $contig->seq($bioseq);
    $bioseq->id($contigid);    

    print STDERR "Contig id " . $contigid . "\n";

    print STDERR "Repeats are " . scalar(@repeats) . "\n";

    foreach my $f (@repeats) {
      $contig->add_RepeatFeature($f);
    }

    foreach my $f (@feat) {
      if ($f->analysis->db ne "") {
	if ($f->score > $threshold) {
	  $f->seqname($contigid);
	  $f->analysis->program_version(1);
	  $contig->add_SeqFeature($f);
	}
      } else {
	$f->seqname($contigid);
	$f->analysis->program_version(1);
	$contig->add_SeqFeature($f);
      }
    }
    
    $clone->add_Contig($contig);
    
    eval {
      $newdb->write_Clone($clone);
      print STDERR "Written ".$clone->id." scaffold into db\n";
    };
    
    if( $@ ) {
      print STDERR "Could not write clone into database, error was $@\n";
    } else {
      my $contig = $newdb->get_Contig($contigid);
      
      # put into the golden path
      
      my $len = ($end - $current + 1);

      my $query = "insert into static_golden_path values('$chr','$chr'," . $contig->internal_id . ",$current,$end,1,$len,1,$len,1,'$newpath')";
      
      my $sth = $newdb->prepare($query);
      
      my $res = $sth->execute;
    
    }
    $current += $chunk;
  }
}


sub print_analysis {
  my ($analysis) = @_;

  print STDERR "Analysis\n";
  print STDERR "Id " . $analysis->id . "\n";
  print STDERR "Db" . $analysis->db . "\n";
  print STDERR "Db_file " . $analysis->db_file . "\n";
  print STDERR "Db_version " . $analysis->db_version . "\n";
  print STDERR "Program " . $analysis->program . "\n";
  print STDERR "Program_version " . $analysis->program_version . "\n";
  print STDERR "Program_file " . $analysis->program_file . "\n";
  print STDERR "Gff_source " . $analysis->gff_source . "\n";
  print STDERR "Gff_feature " . $analysis->gff_feature . "\n";
  print STDERR "Module " . $analysis->module . "\n";
  print STDERR "Module_version " . $analysis->module_version . "\n";
  print STDERR "Parameters " . $analysis->parameters . "\n";
  print STDERR "Created " . $analysis->created . "\n";
  print STDERR "Logic_name " . $analysis->logic_name . "\n";
}

