#!/bin/sh
rm $1.block.gff

export APOLLO_ROOT=../../

for i in `awk '{print $9}' $1.syten.gff |uniq -c |awk '$1 > 100 {print $2}'` ; do
    echo "Processing $i"
    awk '$9 == "'$i'"' $1.syten.gff > t.gff
    java -mx128M -DAPOLLO_ROOT=${APOLLO_ROOT} -classpath ./classfiles:../../data:${CLASSPATH} apollo.gui.SyntenyPanel $1.human.gff mouse/$4.*.mouse.gff t.gff $2 $3 $5 $6
done
