#!/usr/local/bin/perl

use Mysql;

###################################################
# Extremely rough and ready test script to test
# the mysql driver (sans DBI).  Connects to 
# database 'pog' on localhost as mysql user root
# and queries for all features with no analysis id.
#
###################################################
# Author: Michele Clamp 23rd May 1999
###################################################

my $dbh = Mysql->connect('localhost','pog','root');
my $sth = $dbh->query("select * from feature where analysis = \'\'");

print("Query result is $sth\n");
print("Number of rows is " . $sth->numrows . "\n");
print("Number of fields is " . $sth->numfields . "\n");

my @list = $sth->name;

for ($i = 0; $i < $sth->numrows; $i++) {
  my $len = $sth->length->[$i];
  printf("%${len}s ",$list[$i]);
}

printf("\n");

for ($i = 0; $i < $sth->numrows; $i++) {
  my %hash = $sth->fetchhash;

  foreach my $key (keys %hash) {
    my $len = $sth->length->[$i];
    printf("%${len}s ",$hash{$key});
  }

  print("\n");
}
