#!/bin/ksh
perl -I ~/bioperl-live -I ~/pogdir/ensembl/modules/ ./transfer.pl -fdbtype rdb -tdbtype rdb -tdbname small -fdbname ensembl -thost localhost -tmodule Bio::EnsEMBL::DBSQL::Obj -tdbuser root -tdbpass superpog -fdbuser ensro $1 
